apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-manifests
  # The namespace must match the namespace of your Argo CD instance - typically this is argocd.
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: .
    repoURL: https://github.com/dignajar/argocd-kubernetes-resources.git
    targetRevision: main
    directory:
      recurse: true
  destination:
    namespace: '*'
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
